[default]
session_cookie_name = "chat-session-id"
session_data_dir = "/tmp/chat-sessions"
chatbot_path = "/Users/namaya/HuggingFaceHub/models/bloomz-ggml/bloomz-560m-f16.bin"
chatbot_tokenizer_path = "/Users/namaya/HuggingFaceHub/models/bloomz-ggml/tokenizer.json"